ticketkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from cart.views import add_to_cart, cart_detail, remove_item, update_item, checkout,order_detail
from .views import home, RegisterCustomer, user_logout, loginPage, updateUser, updateUserPwd, add_payment_method, add_balance, user_profile


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('',home,name="home"),
    path('add-to-cart/<int:concert_id>',add_to_cart, name="add-to-cart"),
    path('cart-detail/',cart_detail, name="cart-detail"),
    path('order_detail/<int:order_id>',order_detail,name="order-detail"),
    path('remove-item/<int:item_id>',remove_item, name="remove-item"),
    path('update-item/<int:item_id>',update_item, name="update-item"),
    path('checkout/',checkout, name='checkout' ),
    path('register/',RegisterCustomer, name="register"),
    path('logout/',user_logout, name='logout'),
    path('login/',loginPage,name="login"),
    path('update-user/',updateUser,name='update-user'),
    path('change-password/',updateUserPwd, name='change-password'),
    path('add-payment-method/', add_payment_method,name="add-payment-method"),
    path('add-balance/',add_balance,name="add-balance"),
    path('profile',user_profile,name="user-profile")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
import uuid
from django.db.models import Sum, F
from django.db import models
from ticketkartapp.models import User
from concert.models import ConcertTicket

class Cart(models.Model):
    customer = models.OneToOneField(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.customer.name}'s Cart"
    
    @property
    def cart_total(self):
        return self.cartitem_set.annotate(
            item_total=F('quantity') * F('ticket__price')
        ).aggregate(total=Sum('item_total'))['total']

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    ticket = models.ForeignKey(ConcertTicket, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()

    def __str__(self):
        return f'{str(self.ticket)}'



class Order(models.Model):
    placed_at = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(User, on_delete=models.PROTECT)

    @property
    def order_total(self):
        return self.orderitem_set.annotate(
            item_total=F('quantity') * F('ticket__price')
        ).aggregate(total=Sum('item_total'))['total']
    
    def __str__(self) -> str:
        return f"{self.customer.name}'s order Placed at {self.placed_at}"


class OrderItem(models.Model):
    uniq_uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    order = models.ForeignKey(Order, on_delete=models.PROTECT)
    ticket = models.ForeignKey(ConcertTicket, on_delete=models.PROTECT)
    quantity = models.PositiveSmallIntegerField()

    @property
    def unit_price(self):
        return self.ticket.price
    
    def __str__(self):
        return f'{str(self.ticket.concert.name)} - {self.ticket.seat_type}- {self.quantity}'

ticketkartapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from decimal import Decimal


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    phone = models.CharField(max_length=12, null=True, unique=True)
    balance = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    avatar = models.ImageField(null=True, default="avatar.svg")
    is_retailer = models.BooleanField(default=False)

    def __str__(self):
        user_type = "Normal User"
        if self.is_retailer:
            user_type = "Retailer"
        return f'{self.name} - {self.email} - {user_type}' 

    def deduct_balance(self, amount):
        if self.balance >= Decimal(amount):
            self.balance -= Decimal(amount)
            self.save()
            return True
        else:
            return False


class PaymentMethod(models.Model):
    PAYMENT_TYPES = [
        ('CC', 'Credit Card'),
        ('DC', 'Debit Card'),
        ('INT', 'Interac'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_type = models.CharField(choices=PAYMENT_TYPES, max_length=3)
    card_number = models.CharField(max_length=16, null=True)
    expiry_date = models.DateField(null=True)
    cvv = models.CharField(max_length=3, null=True)
    bank_name = models.CharField(max_length=100, null=True)
    account_number = models.CharField(max_length=100, null=True)
    verified = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.name} - {self.get_payment_type_display()}'
    
    def verify(self):
        if self.payment_type == 'CC' or self.payment_type == 'DC':
            # credit/debit card verification here
            # check card number and expiry date against a database
            self.verified = True
            self.save()
            return True
        elif self.payment_type == 'INT':
            # Interac verification here
            # check bank name and account number against a database
            self.verified = True
            self.save()
            return True
        else:
            return False

    def make_payment(self, amount):
        if self.verified:
            # fake payment here
            # send a request to a fake payment gateway and return success or failure
            return True
        else:
            return False

ticketkart/forms.py
from django import forms
from django.forms import ModelForm, TextInput, TimeField, Select,EmailInput,PasswordInput,FileInput, HiddenInput,DateInput
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from ticketkartapp.models import User, PaymentMethod


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','name', 'email', 'phone', 'is_retailer', 'password1', 'password2']
        labels = {
            'username': 'Username',
            'email': 'Email',
            'phone': 'Phone',
            'is_retailer': 'Are you a retailer?',
            'password1': 'Password',
            'password2': 'Confirm Password',
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'avatar','first_name', 'last_name','phone']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'first_name':TextInput(attrs={'class': 'form-control'}),
            'last_name':TextInput(attrs={'class': 'form-control'}),
            'phone':TextInput(attrs={'class': 'form-control'}),
            'avatar':FileInput(attrs={'class': 'form-control'}),
        }

class PwdUpdateForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['password1', 'password2','old_password']
        widgets = {
            'password1': PasswordInput(attrs={'class': 'form-control'}),
            'password2': PasswordInput(attrs={'class': 'form-control'}),
            'old_password': PasswordInput(attrs={'class': 'form-control'}),
        }


class PaymentMethodForm(forms.ModelForm):
    class Meta:
        model = PaymentMethod
        fields = ['payment_type', 'card_number', 'expiry_date', 'cvv']
        widgets = {
            'expiry_date':DateInput(attrs={'class': 'form-control'}),
        }

class BalanceForm(forms.Form):
    amount = forms.DecimalField(max_digits=6, decimal_places=2)

ticketkart/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q, F
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate,  update_session_auth_hash
from concert.models import Concert, ConcertTicket
from cart.models import Cart, CartItem,Order, OrderItem
from ticketkartapp.models import User, PaymentMethod
import datetime
from .forms import CustomUserCreationForm, PwdUpdateForm, UserForm, PaymentMethodForm, BalanceForm
from decimal import Decimal


def home(request):
    today_date=datetime.date.today()
    if request.method == "GET":
        queryset = Concert.objects.filter(date__gte=today_date).order_by("date")
        context = {
            "concerts" : list(queryset)
        }
        return render(request,'home.html',context)
    if request.method == "POST":
        q_name = request.POST.get('concert')
        q_date = request.POST.get('date')
        q_location = request.POST.get('location')
        q_name = q_name.lower()
        q_date = q_date if len(q_date) > 0 else today_date
        queryset_1 = Concert.objects.select_related('venue').filter(Q(date__gte=q_date),Q(name__icontains=q_name),Q(venue__location__icontains=q_location)).order_by("date")
        context_2 = {
        "concerts" : list(queryset_1)
        }
        return render(request, 'home.html', context_2)


@login_required(login_url='login')
def user_logout(request):
    logout(request)
    return redirect('home')

def RegisterCustomer(request):
    if request.user.is_authenticated:
        return redirect('logout')
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'An error occurred during registration')

    return render(request, 'register.html', {'form': form})



@login_required(login_url='login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=request.user)
        print(request.FILES)
        if form.is_valid():
            form.save()
            # print(form.errors)
            return redirect('user-profile')

    return render(request, 'update.html', {'form': form})


@login_required(login_url='login')
def updateUserPwd(request):
    form = PwdUpdateForm(user=request.user)
    if request.method == 'POST':
        form = PwdUpdateForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            return redirect('user-profile')
    else:
        form = PwdUpdateForm(request.user)
    return render(request, 'updatepwd.html', {'form': form})


def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username')
        username = username.lower()
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Username OR password does not exit')

    return render(request, 'login.html')

@login_required(login_url='login')
def add_payment_method(request):

    if request.method == 'POST':
        form = PaymentMethodForm(request.POST)
        if form.is_valid():
            payment_method = form.save(commit=False)
            payment_method.user = request.user
            payment_method.save()
            return redirect('add-balance')
    else:
        form = PaymentMethodForm()

    return render(request, 'add_payment_method.html', {'form': form})




@login_required(login_url='login')
def add_balance(request):
    payment_methods = PaymentMethod.objects.filter(user=request.user)

    if not payment_methods:
        return redirect('add-payment-method')

    if request.method == 'POST':
        form = BalanceForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data.get('amount')
            payment_method_id = request.POST.get('payment_method')
            payment_method = PaymentMethod.objects.get(id=payment_method_id)

            if not payment_method.verified:
                payment_method.verify()
                if not payment_method.verified:
                    return redirect('add_balance')

            if payment_method.make_payment(amount):
                request.user.balance += Decimal(amount)
                request.user.save()
                return redirect('user-profile')
    else:
        form = BalanceForm()

    return render(request, 'add_balance.html', {'form': form, 'payment_methods': payment_methods})


@login_required(login_url='login')
def user_profile(request):
    user = request.user
    orders = Order.objects.filter(customer=user).order_by("-placed_at")[:5]
    payment_methods = PaymentMethod.objects.filter(user=user)

    context = {
        "user" : user,
        "orders" : orders,
        "payment_methods": payment_methods
    }

    return render(request, "profile.html",context)

ticketkart/templates/add_balance.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>TicketKart - book your tickets</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
      .navbar {
        background-image: linear-gradient(to left, darkslategrey, black);
      }
      #body {
        background-color: darkslategray;
      }
      .new {
        max-width: 400px;
        max-height: 200px;
      }
      .card-text {
        font-size: small;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark">
      <div class="container-fluid">
        <h3 class="text-white">
          <a href="/" class="text-white navbar-brand">
            <img src="/images/logo-white.png" width="40px"
            height="40px" alt="" srcset="">
            ticketKart</a>
        </h3>
        <div class="justify-content-end">
          {% if request.user.is_authenticated %}
          <div class="btn-group dropstart">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <img
            src="{{request.user.avatar.url}}"
            alt="Profile Picture"
            width="40px"
            height="40px"
            style="border-radius: 50%"
          />
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/">Home</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'cart-detail' %}">My Cart</a></li>
              <li><a class="dropdown-item" href="{% url 'user-profile' %}">My Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'update-user' %}">Update Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'change-password' %}">Update Password</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
          </div>
          {% else %}

          <!-- Not Logged In -->
          <div class="justify-content-end">
            <a href="{% url 'login' %}" class="btn btn-outline-light">Login</a>
            <a href="{% url 'register' %}" class="btn btn-outline-light"
              >Register</a
            >
          </div>
          {% endif %}
        </div>
      </div>
    </nav>
    <nav class="navbar bg-body-tertiary py-5 navbar-dark">
      <div class="container-fluid">
        <form class="container-fluid" action="/" method="post">
          {% csrf_token %}
          <div class="input-group">
            <input
              type="text"
              class="form-control"
              placeholder="Location"
              value=""
              name="location"
            />
            <input
              type="text"
              class="form-control"
              placeholder="Concert Name"
              aria-label="Username"
              name="concert"
            />
            <input
              type="date"
              class="form-control me-2"
              placeholder="yyyy-mm-dd"
              name="date"
            />
            <button type="submit" class="btn btn-secondary" value="grey">
              Search
            </button>
          </div>
        </form>
        <br />
      </div>
    </nav>
    <br />
    <div class="container" style="max-width: 500px; max-height: 500px;">
        <form method="post" id="myform">
            {% csrf_token %}
            {{ form.as_p }}
            <p>Payment methods:</p>
            <ul>
              {% for pm in payment_methods %}
                <li>
                  <label>
                    <input type="radio" name="payment_method" value="{{ pm.id }}">
                    {{ pm.get_payment_type_display }} - ending in {{ pm.card_number|slice:"-4:" }}
                  </label>
                </li>
              {% endfor %}
            </ul>
            <input type="submit" value="Add Balance" class="btn btn-primary">
          </form>
    </div>
      <script>
        window.addEventListener('load', function() {
            const form = document.querySelector('#myform');
            const paymentMethods = form.querySelectorAll('input[type="radio"][name="payment_method"]');
            const firstPaymentMethod = paymentMethods[0];
        
            // Add Bootstrap classes to form
            form.classList.add('form-inline', 'border', 'p-3');
        
            // Automatically select first payment method
            firstPaymentMethod.checked = true;
        });
        
      </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

ticketkart/templates/add_payment_method.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Adding Payment Cards: {{user.name}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
      .navbar {
        background-image: linear-gradient(to left, darkslategrey, black);
      }
      #body {
        background-color: darkslategray;
      }
      .new {
        max-width: 400px;
        max-height: 200px;
      }
      .card-text {
        font-size: small;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark">
      <div class="container-fluid">
        <h3 class="text-white">
          <a href="/" class="text-white navbar-brand">
            <img src="/images/logo-white.png" width="40px"
            height="40px" alt="" srcset="">
            ticketKart</a>
        </h3>
        <div class="justify-content-end">
          {% if request.user.is_authenticated %}
          <div class="btn-group dropstart">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <img
            src="{{request.user.avatar.url}}"
            alt="Profile Picture"
            width="40px"
            height="40px"
            style="border-radius: 50%"
          />
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/">Home</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'cart-detail' %}">My Cart</a></li>
              <li><a class="dropdown-item" href="{% url 'user-profile' %}">My Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'update-user' %}">Update Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'change-password' %}">Update Password</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
          </div>
          {% else %}

          <!-- Not Logged In -->
          <div class="justify-content-end">
            <a href="{% url 'login' %}" class="btn btn-outline-light">Login</a>
            <a href="{% url 'register' %}" class="btn btn-outline-light"
              >Register</a
            >
          </div>
          {% endif %}
        </div>
      </div>
    </nav>
    <nav class="navbar bg-body-tertiary py-5 navbar-dark">
      <div class="container-fluid">
        <form class="container-fluid" action="/" method="post">
          {% csrf_token %}
          <div class="input-group">
            <input
              type="text"
              class="form-control"
              placeholder="Location"
              value=""
              name="location"
            />
            <input
              type="text"
              class="form-control"
              placeholder="Concert Name"
              aria-label="Username"
              name="concert"
            />
            <input
              type="date"
              class="form-control me-2"
              placeholder="yyyy-mm-dd"
              name="date"
            />
            <button type="submit" class="btn btn-secondary" value="grey">
              Search
            </button>
          </div>
        </form>
        <br />
      </div>
    </nav>
    <br />
   <div class="container" style="max-width: 500px; max-height: 500px;" >
    <form action="" method="post" id="myform">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn btn-primary">Add Card</button>
    </form>
  </div>
  <script>
    window.addEventListener('load', function() {
    const form = document.querySelector('#myform');
    const paymentTypeField = form.querySelector('#id_payment_type');
    const cardNumberField = form.querySelector('#id_card_number');
    const expiryDateField = form.querySelector('#id_expiry_date');
    const cvvField = form.querySelector('#id_cvv');
    const submitButton = form.querySelector('button[type="submit"]');

    // Add Bootstrap classes
    form.classList.add('form-horizontal');
    paymentTypeField.classList.add('form-control');
    cardNumberField.classList.add('form-control');
    expiryDateField.classList.add('form-control');
    cvvField.classList.add('form-control');
    submitButton.classList.add('btn', 'btn-primary');

    // Change expiry date field to a date field
    expiryDateField.type = 'date';
});
  </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

ticketkart/templates/edit_cart_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update {{item}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
      .navbar {
        background-image: linear-gradient(to left, darkslategrey, black);
      }
      #body {
        background-color: darkslategray;
      }
      .new {
        max-width: 400px;
        max-height: 200px;
      }
      .card-text {
        font-size: small;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark">
      <div class="container-fluid">
        <h3 class="text-white">
          <a href="/" class="text-white navbar-brand">
            <img src="/images/logo-white.png" width="40px"
            height="40px" alt="" srcset="">
            ticketKart</a>
        </h3>
        <div class="justify-content-end">
          {% if request.user.is_authenticated %}
          <div class="btn-group dropstart">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <img
            src="{{request.user.avatar.url}}"
            alt="Profile Picture"
            width="40px"
            height="40px"
            style="border-radius: 50%"
          />
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/">Home</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'cart-detail' %}">My Cart</a></li>
              <li><a class="dropdown-item" href="{% url 'user-profile' %}">My Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'update-user' %}">Update Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'change-password' %}">Update Password</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
          </div>
          {% else %}

          <!-- Not Logged In -->
          <div class="justify-content-end">
            <a href="{% url 'login' %}" class="btn btn-outline-light">Login</a>
            <a href="{% url 'register' %}" class="btn btn-outline-light"
              >Register</a
            >
          </div>
          {% endif %}
        </div>
      </div>
    </nav>
    <nav class="navbar bg-body-tertiary py-5 navbar-dark">
      <div class="container-fluid">
        <form class="container-fluid" action="/" method="post">
          {% csrf_token %}
          <div class="input-group">
            <input
              type="text"
              class="form-control"
              placeholder="Location"
              value=""
              name="location"
            />
            <input
              type="text"
              class="form-control"
              placeholder="Concert Name"
              aria-label="Username"
              name="concert"
            />
            <input
              type="date"
              class="form-control me-2"
              placeholder="yyyy-mm-dd"
              name="date"
            />
            <button type="submit" class="btn btn-secondary" value="grey">
              Search
            </button>
          </div>
        </form>
        <br />
      </div>
    </nav>
    <br />
    <div class="container-fluid container" style="max-width: 50%; text-align: center;">
    <h4>Edit Cart Item : {{item}}</h4>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary mr-2">Save</button>
    <a href="{% url 'cart-detail' %}" class="btn btn-secondary">Cancel</a>
  </form>
</div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <script>
    // Select the form elements
    const form = document.querySelector('form');
    const label = document.querySelector('label[for="id_quantity"]');
    const input = document.querySelector('#id_quantity');
    const button = document.querySelector('button[type="submit"]');
    const cancelLink = document.querySelector('a[href="/cart-detail/"]');
  
    // Add Bootstrap classes
    form.classList.add('mt-4');
    label.classList.add('h5', 'mr-3');
    input.classList.add('form-control');
    button.classList.add('btn', 'btn-primary', 'mr-2');
    cancelLink.classList.add('btn', 'btn-secondary');
  
  </script>
</body>
</html>